CREATE TABLE IF NOT EXISTS products(

	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(50),
	SLOGAN VARCHAR(1000),
	DESCRIPTION VARCHAR(1000),
    CATEGORY VARCHAR(50),
	DEFAULT_PRICE FLOAT
);

COPY products FROM '/tmp/product.csv'
DELIMITER ','
CSV HEADER;