
-- row  count is 1958102 ✅

CREATE TABLE IF NOT EXISTS styles(

	STYLE_ID SERIAL PRIMARY KEY,
    PRODUCT_ID INT,
	NAME VARCHAR(50),
	SALE_PRICE INT,
	ORIGINAL_PRICE INT,
	DEFAULT_STYLE BOOLEAN,
    FOREIGN KEY (PRODUCT_ID) REFERENCES products(ID)

);

COPY styles FROM '/tmp/styles.csv'
DELIMITER ','
CSV HEADER
NULL 'null';

